//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Events {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuditEventFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Events.AuditEventFile", typeof(AuditEventFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is unsuccessfully authenticated. {2}..
        /// </summary>
        public static string CreateAccountFailed {
            get {
                return ResourceManager.GetString("CreateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is successfully authenticated..
        /// </summary>
        public static string CreateAccountSuccess {
            get {
                return ResourceManager.GetString("CreateAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} unsuccessfully deposited {1}. {2}..
        /// </summary>
        public static string DepositFailed {
            get {
                return ResourceManager.GetString("DepositFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} request to deposit is unsuccessful. {2}..
        /// </summary>
        public static string DepositRequestFailed {
            get {
                return ResourceManager.GetString("DepositRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} request to deposit is successful..
        /// </summary>
        public static string DepositRequestSuccess {
            get {
                return ResourceManager.GetString("DepositRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully deposited {1}..
        /// </summary>
        public static string DepositSuccess {
            get {
                return ResourceManager.GetString("DepositSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} unsuccessfully reseted pin. {2}..
        /// </summary>
        public static string ResetPinFailed {
            get {
                return ResourceManager.GetString("ResetPinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully reseted pin..
        /// </summary>
        public static string ResetPinSuccess {
            get {
                return ResourceManager.GetString("ResetPinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} unsuccessfully revoked certificate. {2}..
        /// </summary>
        public static string RevokeCertFailed {
            get {
                return ResourceManager.GetString("RevokeCertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully revoked certificate..
        /// </summary>
        public static string RevokeCertSuccess {
            get {
                return ResourceManager.GetString("RevokeCertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} withdrew {1} from {2}, {3} times in {4} seconds. .
        /// </summary>
        public static string WithdrawDetection {
            get {
                return ResourceManager.GetString("WithdrawDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} unsuccessfully withrawn. {2}..
        /// </summary>
        public static string WithdrawFailed {
            get {
                return ResourceManager.GetString("WithdrawFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} request to withdraw is unsuccessful. {2}..
        /// </summary>
        public static string WithdrawRequestFailed {
            get {
                return ResourceManager.GetString("WithdrawRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} request to withdraw is successful..
        /// </summary>
        public static string WithdrawRequestSuccess {
            get {
                return ResourceManager.GetString("WithdrawRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully withdrawn {1}..
        /// </summary>
        public static string WithdrawSuccess {
            get {
                return ResourceManager.GetString("WithdrawSuccess", resourceCulture);
            }
        }
    }
}
